name: Update docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout 🛎️ Doc-builder
        uses: actions/checkout@v3
        with:
          repository: unifyai/doc-builder
          path: .doc-builder

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build docs
        run: |
          ./.doc-builder/make_docs_without_docker.sh ..

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'docs/build'
