name: test-nightly-binaries
on: 
  workflow_dispatch:
  push:

jobs:
  notebook-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          alexnet_demo_cpu,
          resnet_demo_cpu,
          lstm_torch_to_tensorflow_cpu,
          kornia_demo,
          kornia_So3,
        ]

    steps:
        - name: Clean repository
          run:
            sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

        - name: Checkout Demos🛎
          uses: actions/checkout@v4
          with:
            repository: ivy-llc/demos
            path: demos
            persist-credentials: false
            submodules: "recursive"
            fetch-depth: 1

        - name: Checkout Ivy🛎
          uses: actions/checkout@v4
          with:
            repository: ivy-llc/ivy
            path: ivy_repo
            persist-credentials: false
            submodules: "recursive"
            fetch-depth: 1
  
        - name: Run Integration Tests for Enterprise Demos
          run: |
            pip install -e ivy_repo
            pip install -r ivy_repo/requirements/requirements.txt
            pip install -r ivy_repo/requirements/optional.txt
            demos/tests/test_demos.sh examples_and_demos/${{ matrix.module }}.ipynb true true
