name: test-nightly-binaries
on: 
  workflow_dispatch:
  push:

jobs:
  notebook-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [
          alexnet_demo_cpu,
          resnet_demo_cpu,
          lstm_tensorflow_to_torch_cpu,
          lstm_torch_to_tensorflow_cpu,
          kornia_demo,
        ]

    steps:
        - name: Clean repository
          run:
            sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

        - name: Checkout Demos🛎
          uses: actions/checkout@v4
          with:
            repository: ivy-llc/demos
            path: demos
            persist-credentials: false
            submodules: "recursive"
            fetch-depth: 1

        - name: Checkout Ivy🛎
          uses: actions/checkout@v4
          with:
            repository: ivy-llc/ivy
            path: ivy
            persist-credentials: false
            submodules: "recursive"
            fetch-depth: 1
  
        - name: Run Integration Tests for Enterprise Demos
          run: |
            docker pull ivyllc/ivy:latest
            docker run --rm -v "$(pwd)"/demos:/ivy/demos -v "$(pwd)"/ivy:/ivy/ivy ivyllc/ivy:latest demos/tests/test_demos.sh examples_and_demos/${{ matrix.module }}.ipynb true true
